# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(email: 'ferdiarmagan@web.de', username: 'ferdi_amg', password: 'ferdiamg', password_confirmation: 'ferdiamg')
User.create(email: 'maikreinicke@yahoo.de', username: 'prodbykendox', password: 'maik123', password_confirmation: 'maik123')

@beat1 = Beat.find_or_create_by(name: 'Astro', bpm: '130', key: 'F#m', link: 'https://www.dropbox.com/s/8lnnk2ts0wimhnw/Cartii%20Yachty%20C%20Minor%20150BPM%20v2.mp3', user_id: 1)
@beat2 = Beat.find_or_create_by(name: 'Fuego', bpm: '144', key: 'D#m', link: 'https://www.dropbox.com/s/8lnnk2ts0wimhnw/Cartii%20Yachty%20C%20Minor%20150BPM%20v2.mp3', user_id: 1)
@beat3 = Beat.find_or_create_by(name: 'Aliens', bpm: '150', key: 'F#', link: 'https://www.dropbox.com/s/huo1u4d57ubl44k/G%23%20Minor%20PartyNextDoor%20Type%20Beat%20Wus%20Good.mp3', user_id: 2)

@beat1.tag_list.add("Travis Scott")
@beat1.save

@beat2.tag_list.add("Drake")
@beat2.save

@beat3.tag_list.add("Playboi Carti")
@beat3.tag_list.add("Rich The Kid")
@beat3.save

list = ['21 Savage',
        '2 Chainz',
        '3OH!3',
        '50 Cent',
        '6ix9ine',
        '6lack',
        'A Boogie wit da Hoodie',
        'A Tribe Called Quest',
        'Above the Law',
        'Ab-Soul',
        'Ace Hood',
        'Aceyalone',
        'Action Bronson',
        'Aesop Rock',
        'Afrika Bambaataa',
        'Afroman',
        'Akon',
        'Aminé Aminé',
        'Anderson .Paak',
        'ASAP Ferg',
        'ASAP Rocky',
        'Asher Roth',
        'Anthony Cruz AZ',
        'Aubrey Joseph',
        'Audio Two',
        'August Alsina',
        'Ayo & Teo',
        'Azealia Banks',
        'Baby Bash',
        'Bad Azz',
        'Big Boi',
        'Big Daddy Kane',
        'Big Gipp',
        'Big Hawk',
        'Big Kuntry King',
        'Big L',
        'Big Moe',
        'Big Noyd',
        'Big Pokey',
        'Big Punisher',
        'Big Sean',
        'Big Syke',
        'Big Tymers',
        'Birdman',
        'Bizarre',
        'Biz Markie',
        'Bizzy Bone',
        'Blackalicious',
        'The Black Eyed Peas',
        'Black Milk',
        'Black Moon',
        'Black Sheep',
        'Black Star',
        'Blaq Poet',
        'Blaque Ivory',
        'B-Legit',
        'Blocboy JB',
        'Blockhead',
        'Blowfly',
        'B.o.B',
        'Body Count',
        'Bone Crusher',
        'Bone Thugs-N-Harmony',
        'Boogie Down Productions',
        'Boot Camp Clik',
        'Boo-Yaa T.R.I.B.E.',
        'Bow Wow',
        'Bran Nu',
        'Brand Nubian',
        'B-Real',
        'Brotha Lynch Hung',
        'Bryshere Y. Gray',
        'Bryson Tiller',
        'Bubba Sparxxx',
        'Buckshot',
        'Bugz',
        'Bun B',
        'Busdriver',
        'Busta Rhymes',
        'Butterscotch',
        'Mary J. Blige',
        'C-Murder',
        'Cali Agents',
        'Camp Lo',
        'Cam’ron',
        'Candiria',
        'Canibus',
        'Cannibal Ox',
        'Capone-N-Noreaga',
        'Cappadonna',
        'Natalia Cappuccini',
        'Cardi B',
        'Cassidy',
        'C-Bo',
        'Celly Cel',
        'Chamillionaire',
        'Chance The Rapper',
        'Charli Baltimore',
        'Child Rebel Soldier',
        'Chingy',
        'Chino XL',
        'Cirroc Lofton',
        'Chilly Tee',
        'Chris Brown',
        'Chuck D',
        'CJ Mac',
        'clipping.',
        'Clipse',
        'CL Smooth',
        'Cocoa Brovaz',
        'Coke La Rock',
        'Cold 187um',
        'Common',
        'Company Flow',
        'Comptons Most Wanted',
        'Consequence',
        'Cool & Dre',
        'Coolio',
        'Cormega',
        'Cowboy Troy',
        'Craig G',
        'Craig Mack',
        'Crime Mob',
        'Crooked I',
        'Crooklyn Clan',
        'Cuban Link',
        'CunninLynguists',
        'CYNE',
        'Cypress Hill',
        'D12',
        'D4L',
        'Dälek',
        'Da Beatminerz',
        'Da Brat',
        'Da Bush Babees',
        'Da Lench Mob',
        'Dame Grease',
        'Damien Hess',
        'Danja',
        'Danny Brown',
        'Dark Lotus',
        'Dawaun Parker',
        'Das EFX',
        'Dave B',
        'Daveed Diggs',
        'David Banner',
        'David Faustino',
        'Daz Dillinger',
        'D-Block',
        'Deadlee',
        'Dead Prez',
        'Death Grips',
        'Declaime',
        'Deep Puddle Dynamics',
        'Defari',
        'Def Squad',
        'Dej Loaf',
        'De La Soul',
        'Desiigner',
        'Destiny Frasqueri',
        'Deuce',
        'Dev',
        'Devin the Dude',
        'DJ Drama',
        'DJ Khaled',
        'DJ Premier',
        'DJ Whoo Kid',
        'DMX',
        'Doe B',
        'Donald Glover',
        'Dorrough',
        'Doseone',
        'Doug E. Fresh',
        'Drag-On',
        'D.R.A.M.',
        'Dr. Dre',
        'Dreezy',
        'Dresta',
        'Dubb Union',
        'Dungeon Family',
        'E-40',
        'Earl Sweatshirt',
        'Easy Mo Bee',
        'Eazy-E',
        'Egyptian Lover',
        'El-P',
        'Elzhi',
        'Eminem',
        'EPMD',
        'Eric B. & Rakim',
        'Eric IQ Gray',
        'Erick Sermon',
        'Eric Singleton',
        'E.S.G.',
        'Esham',
        'Euro',
        'Eve',
        'Everlast',
        'Evidence',
        'Evil Pimp',
        'Eyedea',
        'Fabolous',
        'Fab 5 Freddy',
        'Far East Movement',
        'Fashawn',
        'Fast Life Yungstaz',
        'The Fat Boys',
        'Fat Joe',
        'Fatman Scoop',
        'Fat Pat',
        'Fermin IV',
        'Fetty Wap',
        'Flatbush Zombies',
        'Flavor Flav',
        'Flipsyde',
        'Flo Rida',
        'Fonzworth Bentley',
        'Fort Minor',
        'Foxy Brown',
        'Frank Waln',
        'Franky Gee',
        'Freddie Gibbs',
        'Fredro Starr',
        'Fredwreck',
        'Freedom Williams',
        'French Montana',
        'The Fugees',
        'Funkdoobiest',
        'Funkmaster Flex',
        'Fu-Schnickens',
        'Future',
        'Future Brown',
        'Game',
        'Gang Starr',
        'Ganksta N-I-P',
        'Gavlyn',
        'G-Eazy',
        'Geto Boys',
        'Ghostface Killah',
        'Gucci Mane',
        'G Unit',
        'Gym Class Heroes',
        'Hail Mary Mallon',
        'Half-A-Mill',
        'Handsome Boy Modeling School',
        'Havoc',
        'Heather B.',
        'Heavy D. & the Boyz',
        'Heltah Skeltah',
        'Hi-Tek',
        'Hieroglyphics',
        'Higher Minds',
        'Ho99o9',
        'Hollywood Undead',
        'Hoodie Allen',
        'Hopsin',
        'Hot Boys',
        'House of Pain',
        'Huey Mack',
        'Hurricane Chris',
        'Iamsu!',
        'Ice Cube',
        'Ice-T',
        'Ill Bill',
        'Illogic',
        'ILoveMakonnen',
        'Infamous Mobb',
        'Jadakiss',
        'Jae Millz',
        'Jake One',
        'Jamal Woolard',
        'Jam Master Jay',
        'Ja Rule',
        'Jay Rock',
        'Jay Z',
        'Jazze Pha',
        'Jazzmatazz',
        'J Dilla',
        'Jean Grae',
        'Jedi Mind Tricks',
        'Jeezy',
        'Jermaine Dupri',
        'Jeru The Damaja',
        'J-five',
        'Jibbs',
        'Jidenna',
        'Jim Jones',
        'J-Kwon',
        'J-Live',
        'Joe Budden',
        'Joell Ortiz',
        'Joey Badass',
        'Joyner Lucas',
        'J. R. Writer',
        'Juelz Santana',
        'Juice Crew',
        'Juice Wrld',
        'Juicy J.',
        'Jungle Brothers',
        'Junior M.A.F.I.A.',
        'Junk Science',
        'Jurassic 5',
        'Just Blaze',
        'Juvenile',
        'Kanye West',
        'Kassa Overall',
        'Katt Williams',
        'K Camp',
        'Keak da Sneak',
        'Keith Murray',
        'Keith Stanfield',
        'Kendrick Lamar',
        'Kenny Muhammad',
        'Kent Jones',
        'Kero One',
        'Kevin Gates',
        'Khia',
        'Kid Cudi',
        'Kid Frost',
        'Kid Ink',
        'Kid n Play',
        'Kids See Ghosts',
        'Killah Priest',
        'Killarmy',
        'Killer Mike',
        'King Tee',
        'Kinto Sol',
        'Kirk Knight',
        'K Love',
        'Kodak Black',
        'Kokane',
        'Kon Artis',
        'Kool DJ Herc',
        'Kool G Rap',
        'Kool Keith',
        'Kool Moe Dee',
        'Kool Rock Steady',
        'Kottonmouth Kings',
        'Krayzie Bone',
        'K-Rino',
        'Kris Kross',
        'Krizz Kaliko',
        'KRS-One',
        'K-Solo',
        'Kuniva',
        'Kurious',
        'Kurtis Blow',
        'Kurupt',
        'Kyle Lucas',
        'La Coka Nostra',
        'Ladell Parks',
        'Large Professor',
        'Lauryn Hill',
        'Layzie Bone',
        'Leaders of the New School',
        'Lecrae',
        'Le1f',
        'Lifers Group',
        'Lil Baby',
        'Lil Boosie',
        'Lil’ Cease',
        'Lil Dicky',
        'Lil’ Flip',
        'Lil’ Kim',
        'Lil Jon',
        'Lil’ Mama',
        'Lil Mouse',
        'Lil Peep',
        'Lil Pump',
        'Lil Scrappy',
        'Lil Skies',
        'Lil Twist',
        'Lil Uzi Vert',
        'Lil Wayne',
        'Lil Xan',
        'Lil Yachty',
        'Left Eye',
        'Litefoot',
        'Little Brother',
        'LL Cool J',
        'Lloyd Banks',
        'Logic',
        'Lords of the Underground',
        'Loon',
        'Lootpack',
        'Lord Finesse',
        'Lovebug Starski',
        'Ludacris',
        'Luis Resto',
        'Luke Christopher',
        'Luke Nasty',
        'Lumidee',
        'Lupe Fiasco',
        'Lyfe Jennings',
        'Lyrics Born',
        'M.I.A.',
        'Mac Dre',
        'Machine Gun Kelly',
        'Mack 10',
        'Macklemore',
        'Mack Maine',
        'Madlib',
        'Maino',
        'Main Source',
        'Malcolm Barrett',
        'Mannie Fresh',
        'Mantronix',
        'Mapei',
        'Mark Morales',
        'Marley Marl',
        'Mary J. Blige',
        'Masta Ace',
        'Masta Killa',
        'Master P',
        'Mathematics',
        'MC Breed',
        'MC Eiht',
        'MC Hammer',
        'MC Lyte',
        'MC Ren',
        'MC Serch',
        'MC Shan',
        'Meech Wells',
        'Meek Mill',
        'Mel-Man',
        'Melle Mel',
        'Mellow Man Ace',
        'Memphis Bleek',
        'Method Man',
        'MF Doom',
        'Michael Franti',
        'Mickey Avalon',
        'Mick Jenkins',
        'Migos',
        'Miilkbone',
        'Mike Fuentes',
        'Mike Jones',
        'Mike Ladd',
        'Mike Will Made It',
        'Miles Brown',
        'Militia',
        'Mims',
        'Missy Elliott',
        'Mitchy Slick',
        'Mobb Deep',
        'Mod Sun',
        'Monie Love',
        'Mos Def',
        'M.O.P.',
        'Mr. Lif',
        'Murphy Lee',
        'Murs',
        'Mysonne',
        'Mystikal',
        'Nas',
        'NATAS',
        'Nate Dogg',
        'Native Tongues Posse',
        'Nature',
        'Naughty by Nature',
        'Necro',
        'Nelly',
        'N.E.R.D',
        'New Boyz',
        'Newcleus',
        'NF',
        'Nicki Minaj',
        'Nine',
        'No I.D.',
        'Non Phixion',
        'N.O.R.E.',
        'Numarx',
        'N.W.A',
        'O.F.T.B.',
        'O. G. Style',
        'Obie Trice',
        'Odd Future Wolf Gang Kill Them All',
        'Offset',
        'OG Maco',
        'OJ da Juiceman',
        'Ol’ Dirty Bastard',
        'Onyx',
        'Optimus Rhyme',
        'Organized Noize',
        'Originoo Gunn Clappaz',
        'O’Shea Jackson junior',
        'O.T. Genasis',
        'Outerspace',
        'Outhere Brothers',
        'OutKast',
        'Outlawz',
        'P$C',
        'Papoose',
        'P. Diddy',
        'Paris',
        'Partners in Kryme',
        'Pastor Troy',
        'Paula Perry',
        'Paul Wall',
        'Peanut Butter Wolf',
        'Percee P',
        'Pete Rock',
        'Pete Rock & CL Smooth',
        'Petey Pablo',
        'Pharoahe Monch',
        'Pharrell Williams',
        'Phil the Agony',
        'Pimp C',
        'Pitbull',
        'Planet Asia',
        'Playaz Circle',
        'Playboi Carti',
        'Plies',
        'PMD',
        'P. M. Dawn',
        'P. M. Sampson',
        'PnB Rock',
        'Polow da Don',
        'Pooh-Man',
        'Post Malone',
        'Pras Michel',
        'Prayers',
        'Prince Paul',
        'Prodigal Sunn',
        'Prodigy',
        'Professor X',
        'Project Pat',
        'Proof',
        'Proyecto Uno',
        'Psycho Realm',
        'Public Enemy',
        'Pusha T',
        'Q-Tip',
        'Quad City DJ’s',
        'Queen Latifah',
        'Queen Pen',
        'Questlove',
        'R. A. the Rugged Man',
        'Raekwon',
        'Rae Sremmurd',
        'Rah Digga',
        'Rahzel',
        'Rakim',
        'Ralph Tresvant',
        'Rappin’ 4-Tay',
        'Rapsody',
        'Rasco',
        'Rashad Smith',
        'Rashid Hadee',
        'Ras Kass',
        'Raury',
        'Red Café',
        'Redman',
        'Reflection Eternal',
        'Remy Ma',
        'Rhymefest',
        'Rich Boy',
        'Rich Homie Quan',
        'Rich the Kid',
        'Rick Ross',
        'Rick Rubin',
        'RJD2',
        'Rob Base and DJ E-Z Rock',
        'Robert Diggs',
        'Rock Steady Crew',
        'Roc Raida',
        'Rockwilder',
        'Romany Malco',
        'Romeo',
        'Roscoe',
        'Roscoe Dash',
        'Roxanne Shanté',
        'Royce da 5′9″',
        'Ruff Ryders',
        'Run-D.M.C.',
        'Run the Jewels',
        'Russ',
        'Russell Simmons',
        'Ryu',
        'RZA',
        'Sadat X',
        'Sadistik',
        'Sage Francis',
        'Sage the Gemini',
        'Saigon',
        'Salt ’n’ Pepa',
        'Samiyam',
        'Sammy Adams',
        'Sam Sneed',
        'Sandy y Papo',
        'Saul Williams',
        'Scarface',
        'Schoolboy Q',
        'Schoolly D',
        'Sean Paul',
        'Sebastian',
        'Sha Money XL',
        'Shar Jackson',
        'Shawnna',
        'Sheek Louch',
        'Shlohmo',
        'Shock G',
        'Shop Boyz',
        'Shyne',
        'Silentó',
        'Silkk the Shocker',
        'Sirah',
        'Sir Jinx',
        'Sir Mix-a-Lot',
        'Sister Souljah',
        'Sisyphus',
        'Skee-Lo',
        'Ski Mask the Slump God',
        'Slaughterhouse',
        'Sleepy Brown',
        'Slick Rick',
        'Slim 400',
        'Slim Thug',
        'Slug',
        'Slum Village',
        'Smif-N-Wessun',
        'Smokepurpp',
        'Smokin’ Suckaz wit Logic',
        'Snoop Dogg',
        'Sonny Sandoval',
        'Soopafly',
        'SoShy',
        'Soul Assassins',
        'Soulja Boy',
        'South Central Cartel',
        'SpaceGhostPurrp',
        'Stat Quo',
        'Statik Selektah',
        'Styles P.',
        'Suga-T',
        'Suicideboys',
        'Supaman',
        'Swift',
        'Swizz Beatz',
        'T-Bone',
        'Taboo',
        'Tag Team',
        'Talib Kweli',
        'Tash',
        'Tech N9ne',
        'Tha Alkaholiks',
        'The Notorious B.I.G.',
        'The Roots',
        'The Underachievers',
        'Thirstin Howl III',
        'Three 6 Mafia',
        'Thundercat',
        'T.I.',
        'Timbaland',
        'Trae',
        'Travis Knight',
        'Travis Scott',
        'Tru',
        'Tupac Shakur',
        'Ty Dolla Sign',
        'Tyga',
        'Tyler, the Creator',
        'Vanilla Ice',
        'Vico C',
        'Vince Staples',
        'Vinnie Paz',
        'Wale',
        'Warren G',
        'Why?',
        'Wildchild',
        'Will.i.am',
        'Will Smith',
        'Wiz Khalifa',
        'World Class Wreckin’ Cru',
        'Wu-Tang Clan',
        'Wyclef Jean',
        'X-Clan',
        'XXXTentacion',
        'Xzibit',
        'Ya Boy',
        'Yelawolf',
        'Yella Boy',
        'YG',
        'Ying Yang Twins',
        'Yo Gotti',
        'Youngboy Never Broke Again',
        'Young Buck',
        'Young Chop',
        'Young Dirty Bastard',
        'Young Dolph',
        'Young Gunz',
        'Young Money',
        'Young Noble',
        'Young Thug',
        'Drake',
        'Kid Koala',
        'Nav',
        'Night Lovell',
        'Tory Lanez',
        'Ali Bumaye',
        'Al-Gear',
        'Alpa Gun',
        'Animus',
        'Azad',
        'Azzi Memo',
        'Bonez MC',
        'Bushido',
        'Capital Bra',
        'Capo',
        'Casper',
        'Chefket',
        'Cro',
        'Danju',
        'Dardan',
        'Eko Fresh',
        'Eno',
        'Fard',
        'Farid Bang',
        'Fatal',
        'Fler',
        'GZUZ',
        'Gringo',
        'Haftbefehl',
        'Hanybal',
        'Hasan.K',
        'JAZN',
        'Karate Andi',
        'KC Rebell',
        'Kay One',
        'Kianush',
        'Kollegah',
        'Kontra K',
        'Kool Savas',
        'Kurdo',
        'Luciano',
        'LX',
        'Majoe',
        'Manuellsen',
        'Massiv',
        'Maxwell',
        'Mert',
        'Metrickz',
        'Milonair',
        'M.O.030',
        'Moe Phoenix',
        'Mosh36',
        'MoTrip',
        'Nate57',
        'Nimo',
        'Omik K.',
        'PA Sports',
        'Plusmacher',
        'Prinz Pi',
        'RAF Camora',
        'RIN',
        'Sa4',
        'SadiQ',
        'Samy Deluxe',
        'Schwesta Ewa',
        'Sido',
        'Sinan-G',
        'Silla',
        'SSIO',
        'Sun Diego',
        'Summer Cem',
        'UFO361',
        'Veysel',
        'Xatar',
        'Yung Hurn',
        '187 Strassenbande',
        'AK Ausserkontrolle',
        'Celo & Abdi']

list.each do |tag|
  ActsAsTaggableOn::Tag.new(:name => tag).save
end